import { v4 as uuidv4 } from "uuid";

export const tags = [
  "healthy recipe ideas",
  "healthy recipes",
  "healthy food",
  "nutrition",
  "foods you must try",
  "clean eating",
  "healthy fats",
  "10 foods you must try",
  "healthy",
];

export const playlists = [
  {
    id: "PLEpwurODsrVMtU5aDhkzOwcVFATR6DBsC",
    name: "Favourites",
    videoList: [
      {
        id: uuidv4(),
        publishedAt: "2021-03-03T20:01:04Z",
        channelId: "UCZB32syI0FFtThd6xkPTRrg",
        title:
          "10 UNDERRATED HEALTHY FOODS | Staples I Eat Every Week + How To Use Them!",
        description:
          "ORDER NOW! The HealthNut Cookbook: http://bit.ly/33XUK5l​​​​​\nJoin Our Email List: http://bit.ly/2FwMD6Q​​​​​  \nShop BeautyNut Skincare: http://bit.ly/2NuCNGm​​​​​\nBrowse HealthNut Shop: https://bit.ly/3nyDNIk​​​​​ \n\nToday I'm sharing 10 underrated healthy foods that I think you NEED to try if you haven't already yet! What is your favourite healthy food product that you feel doesn't get enough love and attention? Let me know in the comments below so I can add them to my grocery shopping list and give them a try!⁠\n\nPRODUCTS SEEN/MENTIONED:\n- Medjool Dates: https://amzn.to/3bYmMDg\n- Sea Salt: https://amzn.to/3bWtee6\n- Maldon Sea Salt Flakes: https://amzn.to/3sEulWH\n- Dead Sea Salt: \n- Ghee: https://rstyle.me/+4fu76j-dRgafhwABTszPXQ\n- Coconut Butter (or Manna): https://amzn.to/381QMNJ \n- Nutritional Yeast: https://amzn.to/3e2Op0P \n- Dijon Mustard: https://rstyle.me/+REZp0oOp0v5okW5uZAdaSw \n- Tahini: https://amzn.to/3bThY29\n- Apple Cider Vinegar: https://rstyle.me/+klwJHlE0lHwUlE-QxR51mA \n- Capers (Savor): https://rstyle.me/+ftgGdW6id84Bjon1zHH7_w \n- Avocado Oil: https://amzn.to/3bagh1d\n\nLINKS:\n- Healthy Hacks Playlist (List Style Videos): https://bit.ly/3e52bA0\n- 5 Minute Dairy-Free Cesar Dressing: http://bit.ly/2D0F0Dp \n- Chewy Trail Mix Granola Bars: http://bit.ly/2q6puz0\n- Lemon-Glazed Blueberry Muffins (from the HealthNut Cookbook): http://bit.ly/33XUK5l​​​​​\n- Easy Veggie Hummus Dips 3 Ways: http://bit.ly/2DsZZjD\n- 3 Healthy Summer Salad Dressing Recipes: https://bit.ly/384khyb\n______________________\n\nHey HealthNuts, welcome to my corner of the internet! My name is Nikole and I’m the face behind HealthNut Nutrition. Here on my YouTube channel, I talk about all things food, self-care, wellness, lifestyle, motherhood and our little family of four! I post a NEW video every Wednesday and Friday at 3 pm EST, such as What I Eat In a Day, Healthy Recipes, Lifestyle Vlogs, Healthy Grocery Hauls, Routines and MORE! Welcome to the HealthNut fam and I hope you enjoy watching!\n\nMost Popular Videos: \nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c​​​​​\n7 Life-Changing Healthy Habits to Start TODAY! • https://bit.ly/3nmnCxk​​​​​ \nWhat I Eat In A Day For Anxiety | Healthy & Balanced Meals • https://bit.ly/38jZh7j​​​​​\nFINDING OUT I’M PREGNANT! Pregnancy Test + Emotional Reaction • https://bit.ly/38gxLrb​​​​​ \nHealthy Costco Hauls | Stocking Up On Essentials! • https://bit.ly/38kmc29​​​​​ \n\nOther Places You Can Find Me:\nInstagram • http://Instagram.com/healthnutnutriti...​\nFacebook • https://www.facebook.com/healthnutnut...​... \nBlog • http://www.healthnutnutrition.ca​​​​​  \nShop • https://healthnutshop.com/​​​​​ \nPinterest • https://www.pinterest.ca/healthnutnut...​... \n______________________\n\n*This video is not sponsored. All opinions expressed are my own. Occasionally, I receive products from brands for consideration but will disclose when videos are sponsored and when I am getting paid to talk about the brand/products mentioned. Thank you for your support! \n\nHugs + Smoothies,\nNikole xo",
        thumbnailUrl: "https://i.ytimg.com/vi/yTt8WPRNLco/maxresdefault.jpg",
        channelTitle: "HealthNut Nutrition",
        tags: [
          "healthy recipe ideas",
          "healthy recipes",
          "healthy food",
          "healthy food channel",
          "what to buy at the grocery store",
          "nutritional yeast",
          "healthy grocery haul",
          "what i eat in a week",
          "health nut nutrition",
          "underrated",
          "nutrition",
          "foods you must try",
          "clean eating",
          "healthy fats",
          "pantry essentials",
          "what's in my pantry",
          "underrated healthy foods",
          "10 foods you must try",
          "healthnut",
          "healthnut nutrition",
          "healtnut eats",
          "easy recipes",
          "healthy",
        ],
        duration: "PT14M40S",
        dimension: "2d",
        definition: "hd",
        viewCount: "36953",
        likeCount: "1319",
        dislikeCount: "15",
        favoriteCount: "0",
        commentCount: "99",
      },
    ],
  },
];

export const likedVideos = [
  {
    id: "U_l75ABauHw",
    publishedAt: "2021-02-10T19:59:34Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "10 Simple Cooking Hacks EVERYONE Should Know!",
    description:
      "In today’s video, I’m sharing 10 simple cooking hacks that everyone should know! These cooking hacks are fun, unique and will be sure to blow your mind next time you’re in the kitchen! A huge thank you to Natura Market for sponsoring and this video and supporting the HealthNut community. Click here to visit their website: http://bit.ly/2N2rHKA and stock up on some of their health food goodies! Happy shopping😊\n\nLINKS:\n10 Simple Cooking Hacks Everyone Should Know Blog Post: https://bit.ly/3a8bblt\nHealthy Hacks Playlist: http://bit.ly/3tJBUN9\n10 Life-Changing Baking Hacks That You NEED To Know: https://bit.ly/3aRl5Hx\n\nORDER NOW! The HealthNut Cookbook: http://bit.ly/33XUK5l​​\nJoin Our Email List: http://bit.ly/2FwMD6Q​​  \nShop BeautyNut Skincare: http://bit.ly/2NuCNGm​​\nBrowse HealthNut Shop: https://bit.ly/3nyDNIk​​ \n______________________\n\nHey HealthNuts, welcome to my corner of the internet! My name is Nikole and I’m the face behind HealthNut Nutrition. Here on my YouTube channel, I talk about all things food, self-care, wellness, lifestyle, motherhood and our little family of four! I post a NEW video every Wednesday and Friday at 3 pm EST, such as What I Eat In a Day, Healthy Recipes, Lifestyle Vlogs, Healthy Grocery Hauls, Routines and MORE! Welcome to the HealthNut fam and I hope you enjoy watching!\n\nMost Popular Videos: \nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c​​\n7 Life-Changing Healthy Habits to Start TODAY! • https://bit.ly/3nmnCxk​​ \nWhat I Eat In A Day For Anxiety | Healthy & Balanced Meals • https://bit.ly/38jZh7j​​\nFINDING OUT I’M PREGNANT! Pregnancy Test + Emotional Reaction • https://bit.ly/38gxLrb​​ \nHealthy Costco Hauls | Stocking Up On Essentials! • https://bit.ly/38kmc29​​ \n\nOther Places You Can Find Me:\nInstagram • http://Instagram.com/healthnutnutrition​​\nFacebook • https://www.facebook.com/healthnutnut​​... \nBlog • http://www.healthnutnutrition.ca​​  \nShop • https://healthnutshop.com/​​ \nPinterest • https://www.pinterest.ca/healthnutnut​​... \n______________________\n\n*This video is sponsored. All opinions expressed are my own. Occasionally, I receive products from brands for consideration but will disclose when videos are sponsored and when I am getting paid to talk about the brand/products mentioned. Thank you for your support! \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/U_l75ABauHw/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "kitchen hacks",
      "food hacks",
      "healthy food hacks",
      "healthy eating hacks",
      "healthy kitchen",
      "healthy food tips",
      "healthy eating tips",
      "simple living",
      "cooking hacks",
      "life changing cooking hacks",
      "easy recipes",
      "naturamarket",
      "naturamarket haul",
      "healthy food haul",
      "simple cooking",
      "simple cooking hacks",
      "healthnut",
      "healthnut nutrition",
      "healthnut eats",
      "healthnut hacks",
    ],
    duration: "PT11M6S",
    dimension: "2d",
    definition: "hd",
    viewCount: "40392",
    likeCount: "1686",
    dislikeCount: "31",
    favoriteCount: "0",
    commentCount: "110",
  },
];

export const videoData = [
  {
    id: "yTt8WPRNLco",
    publishedAt: "2021-03-03T20:01:04Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title:
      "10 UNDERRATED HEALTHY FOODS | Staples I Eat Every Week + How To Use Them!",
    description:
      "ORDER NOW! The HealthNut Cookbook: http://bit.ly/33XUK5l​​​​​\nJoin Our Email List: http://bit.ly/2FwMD6Q​​​​​  \nShop BeautyNut Skincare: http://bit.ly/2NuCNGm​​​​​\nBrowse HealthNut Shop: https://bit.ly/3nyDNIk​​​​​ \n\nToday I'm sharing 10 underrated healthy foods that I think you NEED to try if you haven't already yet! What is your favourite healthy food product that you feel doesn't get enough love and attention? Let me know in the comments below so I can add them to my grocery shopping list and give them a try!⁠\n\nPRODUCTS SEEN/MENTIONED:\n- Medjool Dates: https://amzn.to/3bYmMDg\n- Sea Salt: https://amzn.to/3bWtee6\n- Maldon Sea Salt Flakes: https://amzn.to/3sEulWH\n- Dead Sea Salt: \n- Ghee: https://rstyle.me/+4fu76j-dRgafhwABTszPXQ\n- Coconut Butter (or Manna): https://amzn.to/381QMNJ \n- Nutritional Yeast: https://amzn.to/3e2Op0P \n- Dijon Mustard: https://rstyle.me/+REZp0oOp0v5okW5uZAdaSw \n- Tahini: https://amzn.to/3bThY29\n- Apple Cider Vinegar: https://rstyle.me/+klwJHlE0lHwUlE-QxR51mA \n- Capers (Savor): https://rstyle.me/+ftgGdW6id84Bjon1zHH7_w \n- Avocado Oil: https://amzn.to/3bagh1d\n\nLINKS:\n- Healthy Hacks Playlist (List Style Videos): https://bit.ly/3e52bA0\n- 5 Minute Dairy-Free Cesar Dressing: http://bit.ly/2D0F0Dp \n- Chewy Trail Mix Granola Bars: http://bit.ly/2q6puz0\n- Lemon-Glazed Blueberry Muffins (from the HealthNut Cookbook): http://bit.ly/33XUK5l​​​​​\n- Easy Veggie Hummus Dips 3 Ways: http://bit.ly/2DsZZjD\n- 3 Healthy Summer Salad Dressing Recipes: https://bit.ly/384khyb\n______________________\n\nHey HealthNuts, welcome to my corner of the internet! My name is Nikole and I’m the face behind HealthNut Nutrition. Here on my YouTube channel, I talk about all things food, self-care, wellness, lifestyle, motherhood and our little family of four! I post a NEW video every Wednesday and Friday at 3 pm EST, such as What I Eat In a Day, Healthy Recipes, Lifestyle Vlogs, Healthy Grocery Hauls, Routines and MORE! Welcome to the HealthNut fam and I hope you enjoy watching!\n\nMost Popular Videos: \nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c​​​​​\n7 Life-Changing Healthy Habits to Start TODAY! • https://bit.ly/3nmnCxk​​​​​ \nWhat I Eat In A Day For Anxiety | Healthy & Balanced Meals • https://bit.ly/38jZh7j​​​​​\nFINDING OUT I’M PREGNANT! Pregnancy Test + Emotional Reaction • https://bit.ly/38gxLrb​​​​​ \nHealthy Costco Hauls | Stocking Up On Essentials! • https://bit.ly/38kmc29​​​​​ \n\nOther Places You Can Find Me:\nInstagram • http://Instagram.com/healthnutnutriti...​\nFacebook • https://www.facebook.com/healthnutnut...​... \nBlog • http://www.healthnutnutrition.ca​​​​​  \nShop • https://healthnutshop.com/​​​​​ \nPinterest • https://www.pinterest.ca/healthnutnut...​... \n______________________\n\n*This video is not sponsored. All opinions expressed are my own. Occasionally, I receive products from brands for consideration but will disclose when videos are sponsored and when I am getting paid to talk about the brand/products mentioned. Thank you for your support! \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/yTt8WPRNLco/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "healthy recipe ideas",
      "healthy recipes",
      "healthy food",
      "healthy food channel",
      "what to buy at the grocery store",
      "nutritional yeast",
      "healthy grocery haul",
      "what i eat in a week",
      "health nut nutrition",
      "underrated",
      "nutrition",
      "foods you must try",
      "clean eating",
      "healthy fats",
      "pantry essentials",
      "what's in my pantry",
      "underrated healthy foods",
      "10 foods you must try",
      "healthnut",
      "healthnut nutrition",
      "healtnut eats",
      "easy recipes",
      "healthy",
    ],
    duration: "PT14M40S",
    dimension: "2d",
    definition: "hd",
    viewCount: "37395",
    likeCount: "1328",
    dislikeCount: "15",
    favoriteCount: "0",
    commentCount: "99",
  },
  {
    id: "UP4m4d7uje0",
    publishedAt: "2021-02-24T20:15:50Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "HOW TO MEAL PLAN FOR THE WEEK + Healthy Protein Ball Recipe",
    description:
      "ORDER NOW! The HealthNut Cookbook: http://bit.ly/33XUK5l​​​​\nJoin Our Email List: http://bit.ly/2FwMD6Q​​​​  \nShop BeautyNut Skincare: http://bit.ly/2NuCNGm​​​​\nBrowse HealthNut Shop: https://bit.ly/3nyDNIk​​​​ \n\nToday we're getting busy in the kitchen as I share my highly requested meal planning process as a new mama + a healthy protein ball recipe that we've been loving lately! A huge thank you to Garden of Life for collaborating with me on this video and click here: https://bit.ly/3bvhFdQ to shop their plant-based protein powder! What do you guys do to meal plan or prep for the week? Let me know in the comments below!\n\nLINKS:\nHow To Meal Plan for The Week Blog Post + Healthy Protein Ball Recipe: https://bit.ly/3uwhesr\nMeal Planner and Grocery List Bundle (use code \"MEALPLAN\" for 20% off): http://bit.ly/2Id3dde\nFridge Organization Video: https://bit.ly/2Zsysca \nPinterest Page: https://bit.ly/3smtl9s\n\nPRODUCTS SEEN/MENTIONED:\nReusable Produce Bags: http://bit.ly/2XVwUIZ​  \nIce Cream Scoop: http://bit.ly/2uLMhmd\nYellow Stand Mixer: https://amzn.to/2Ic6uuf \nCeramic Knives: http://bit.ly/2xA2WdC\nReusable Produce Bags: http://bit.ly/2XVwUIZ \nSalad Spinner: https://amzn.to/3f95zI6 \n______________________\n\nHey HealthNuts, welcome to my corner of the internet! My name is Nikole and I’m the face behind HealthNut Nutrition. Here on my YouTube channel, I talk about all things food, self-care, wellness, lifestyle, motherhood and our little family of four! I post a NEW video every Wednesday and Friday at 3 pm EST, such as What I Eat In a Day, Healthy Recipes, Lifestyle Vlogs, Healthy Grocery Hauls, Routines and MORE! Welcome to the HealthNut fam and I hope you enjoy watching!\n\nMost Popular Videos: \nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c​​​​\n7 Life-Changing Healthy Habits to Start TODAY! • https://bit.ly/3nmnCxk​​​​ \nWhat I Eat In A Day For Anxiety | Healthy & Balanced Meals • https://bit.ly/38jZh7j​​​​\nFINDING OUT I’M PREGNANT! Pregnancy Test + Emotional Reaction • https://bit.ly/38gxLrb​​​​ \nHealthy Costco Hauls | Stocking Up On Essentials! • https://bit.ly/38kmc29​​​​ \n\nOther Places You Can Find Me:\nInstagram • http://Instagram.com/healthnutnutriti...​\nFacebook • https://www.facebook.com/healthnutnut​​​​... \nBlog • http://www.healthnutnutrition.ca​​​​  \nShop • https://healthnutshop.com/​​​​ \nPinterest • https://www.pinterest.ca/healthnutnut​​​​... \n______________________\n\n*This video is sponsored. All opinions expressed are my own. Occasionally, I receive products from brands for consideration but will disclose when videos are sponsored and when I am getting paid to talk about the brand/products mentioned. Thank you for your support! \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/UP4m4d7uje0/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "weekly meal plan",
      "meal planning tips",
      "save money on food",
      "meal planning",
      "meal plan",
      "how to meal plan",
      "easy meal planning",
      "meal planning for beginners",
      "meal planning ideas",
      "meal planning for the week",
      "how to meal plan for beginners",
      "easy meal planning tips",
      "how I meal plan",
      "protein balls",
      "healthy recipes",
      "meal prep",
      "healthy protein ball recipe",
      "healthnut",
      "healthnut nutrition",
      "healthnut nutrition meal plan",
    ],
    duration: "PT13M14S",
    dimension: "2d",
    definition: "hd",
    viewCount: "52562",
    likeCount: "1825",
    dislikeCount: "13",
    favoriteCount: "0",
    commentCount: "109",
  },
  {
    id: "U_l75ABauHw",
    publishedAt: "2021-02-10T19:59:34Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "10 Simple Cooking Hacks EVERYONE Should Know!",
    description:
      "In today’s video, I’m sharing 10 simple cooking hacks that everyone should know! These cooking hacks are fun, unique and will be sure to blow your mind next time you’re in the kitchen! A huge thank you to Natura Market for sponsoring and this video and supporting the HealthNut community. Click here to visit their website: http://bit.ly/2N2rHKA and stock up on some of their health food goodies! Happy shopping😊\n\nLINKS:\n10 Simple Cooking Hacks Everyone Should Know Blog Post: https://bit.ly/3a8bblt\nHealthy Hacks Playlist: http://bit.ly/3tJBUN9\n10 Life-Changing Baking Hacks That You NEED To Know: https://bit.ly/3aRl5Hx\n\nORDER NOW! The HealthNut Cookbook: http://bit.ly/33XUK5l​​\nJoin Our Email List: http://bit.ly/2FwMD6Q​​  \nShop BeautyNut Skincare: http://bit.ly/2NuCNGm​​\nBrowse HealthNut Shop: https://bit.ly/3nyDNIk​​ \n______________________\n\nHey HealthNuts, welcome to my corner of the internet! My name is Nikole and I’m the face behind HealthNut Nutrition. Here on my YouTube channel, I talk about all things food, self-care, wellness, lifestyle, motherhood and our little family of four! I post a NEW video every Wednesday and Friday at 3 pm EST, such as What I Eat In a Day, Healthy Recipes, Lifestyle Vlogs, Healthy Grocery Hauls, Routines and MORE! Welcome to the HealthNut fam and I hope you enjoy watching!\n\nMost Popular Videos: \nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c​​\n7 Life-Changing Healthy Habits to Start TODAY! • https://bit.ly/3nmnCxk​​ \nWhat I Eat In A Day For Anxiety | Healthy & Balanced Meals • https://bit.ly/38jZh7j​​\nFINDING OUT I’M PREGNANT! Pregnancy Test + Emotional Reaction • https://bit.ly/38gxLrb​​ \nHealthy Costco Hauls | Stocking Up On Essentials! • https://bit.ly/38kmc29​​ \n\nOther Places You Can Find Me:\nInstagram • http://Instagram.com/healthnutnutrition​​\nFacebook • https://www.facebook.com/healthnutnut​​... \nBlog • http://www.healthnutnutrition.ca​​  \nShop • https://healthnutshop.com/​​ \nPinterest • https://www.pinterest.ca/healthnutnut​​... \n______________________\n\n*This video is sponsored. All opinions expressed are my own. Occasionally, I receive products from brands for consideration but will disclose when videos are sponsored and when I am getting paid to talk about the brand/products mentioned. Thank you for your support! \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/U_l75ABauHw/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "kitchen hacks",
      "food hacks",
      "healthy food hacks",
      "healthy eating hacks",
      "healthy kitchen",
      "healthy food tips",
      "healthy eating tips",
      "simple living",
      "cooking hacks",
      "life changing cooking hacks",
      "easy recipes",
      "naturamarket",
      "naturamarket haul",
      "healthy food haul",
      "simple cooking",
      "simple cooking hacks",
      "healthnut",
      "healthnut nutrition",
      "healthnut eats",
      "healthnut hacks",
    ],
    duration: "PT11M6S",
    dimension: "2d",
    definition: "hd",
    viewCount: "40392",
    likeCount: "1686",
    dislikeCount: "31",
    favoriteCount: "0",
    commentCount: "110",
  },
  {
    id: "gNPPpmNEHDY",
    publishedAt: "2021-02-03T19:59:33Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 Daily Healthy Habits as a New Mom + 5 Minute Oral Care Routine",
    description:
      "ORDER NOW! The HealthNut Cookbook: http://bit.ly/33XUK5l​\nJoin Our Email List: http://bit.ly/2FwMD6Q​  \nShop BeautyNut Skincare: http://bit.ly/2NuCNGm​\nBrowse HealthNut Shop: https://bit.ly/3nyDNIk​ \n\nToday I’m sharing 7 habits for a healthy routine as a new mama + my 5-minute oral hygiene routine! A special thank you to Arm & Hammer for sponsoring and collaborating with me on the video and for keeping my teeth clean with only the essential ingredients. \n\nPurchase Arm & Hammer Essentials\nA&H Essentials Charcoal: http://bit.ly/3oJkFHQ \nA&H Essentials Whiten + Strengthen: http://bit.ly/2MP3gAg \nA&H Essentials Healthy Teeth & Gums: https://amzn.to/36ADCqi \n \nLearn More: \nA&H Essentials Charcoal: https://bit.ly/3tkXWWe\nA&H Essentials Whiten + Strengthen: https://bit.ly/3tyFjyi\nA&H Essentials Healthy Teeth & Gums: https://bit.ly/3tntyKJ\n\nLINKS:\n7 Healthy Habits Blog Post: https://bit.ly/2O5LvgT\nMatt’s YouTube Channel: https://bit.ly/3qDDrBT​\n______________________\n\nHey HealthNuts, welcome to my corner of the internet! My name is Nikole and I’m the face behind HealthNut Nutrition. Here on my YouTube channel, I talk about all things food, self-care, wellness, lifestyle, motherhood and our little family of four! I post a NEW video every Wednesday and Friday at 3 pm EST, such as What I Eat In a Day, Healthy Recipes, Lifestyle Vlogs, Healthy Grocery Hauls, Routines and MORE! Welcome to the HealthNut fam and I hope you enjoy watching!\n\nMost Popular Videos: \nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c​\n7 Life-Changing Healthy Habits to Start TODAY! • https://bit.ly/3nmnCxk​ \nWhat I Eat In A Day For Anxiety | Healthy & Balanced Meals • https://bit.ly/38jZh7j​\nFINDING OUT I’M PREGNANT! Pregnancy Test + Emotional Reaction • https://bit.ly/38gxLrb​ \nHealthy Costco Hauls | Stocking Up On Essentials! • https://bit.ly/38kmc29​ \n\nOther Places You Can Find Me:\nInstagram • http://Instagram.com/healthnutnutrition​\nFacebook • https://www.facebook.com/healthnutnut​... \nBlog • http://www.healthnutnutrition.ca​  \nShop • https://healthnutshop.com/​ \nPinterest • https://www.pinterest.ca/healthnutnut​... \n______________________\n\nCamera & Equipment:\nVlogs •\nMain Camera: https://amzn.to/38YF1am​ \nMicrophone: https://amzn.to/3hSlJrm​ \nMini Tripod:  https://amzn.to/3b9W6kh​ \nMain Videos •\nMain Camera: https://amzn.to/3hIKQwH​ \nLens:  https://amzn.to/3pS7FAN​ \nZoom Lens:  https://amzn.to/3b712Xf​ \nGimbal Stabilizer: https://amzn.to/3nbvG44​ \nMicrophone System: https://amzn.to/2JPgdco​  \nTripod: https://amzn.to/3hWz9Tj​ \nC-Stand: https://amzn.to/3q3ZEJl​ \nLighting https://amzn.to/2MEFZkN​ \nDome Diffuser: https://amzn.to/3hSnDIw​  \nClamps: https://amzn.to/3hLwJ9L​ \nSandbags: https://amzn.to/3pJu1o6​  \nBackdrops •\nPecan: https://bit.ly/357MBhR​\nCoral: https://bit.ly/3943GKD​ \nBlue Mist: https://bit.ly/2L7yKBb​ \nLemonade: https://bit.ly/3bbnbUo​\n\n*This video is sponsored. All opinions expressed are my own. Occasionally, I receive products from brands for consideration but will disclose when videos are sponsored and when I am getting paid to talk about the brand/products mentioned. Thank you for your support! \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/gNPPpmNEHDY/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "healthy habits",
      "change your life",
      "how to be healthy",
      "7 healthy habits",
      "new year's resolutions",
      "healthy",
      "green smoothie",
      "healthy smoothie recipes",
      "healthy hacks",
      "daily habits",
      "motivation",
      "inspiration",
      "wellness",
      "lifestyle",
      "meal prep",
      "meal prep hacks",
      "healthnut",
      "healthnut nutrition",
      "recipes",
      "easy recipes",
      "new mom",
      "motherhood",
      "oral care",
      "oral care routine",
      "clean oral care routine",
      "non toxic oral care",
      "healthy lifestyle",
      "healthy living",
    ],
    duration: "PT16M12S",
    dimension: "2d",
    definition: "hd",
    viewCount: "355498",
    likeCount: "1580",
    dislikeCount: "24",
    favoriteCount: "0",
    commentCount: "108",
  },
  {
    id: "GW7ik6G0uZM",
    publishedAt: "2020-08-26T19:04:29Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 Health Hacks You NEED to Try!",
    description:
      "ORDER NOW! The HealthNut Cookbook\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nHey, HealthNuts! Today’s I’m sharing 7 Healthy Eating Hacks. These are simple, straightforward forward and affordable habits that will make a big impact on your health and how you feel overall! Which healthy eating hack are you most inspired to try first? Let me know in the comments below! \n\nA huge thank you to Enerex for sponsoring this video and supporting the HealthNut community. Use Code HEALTHNUT2020 for $2 off their supplements for the next month! : https://enerex.ca/\n\nLINKS:\n7 Health Hacks (+ Recipes Mentioned): https://bit.ly/32rdATn\n7 Must-Know Food Waste Hacks: https://bit.ly/3aZ5gxX\nLemon-Glazed Blueberry Muffin Recipe: (The HealthNut Cookbook) http://bit.ly/33XUK5l\n \nPRODUCTS MENTIONED:\nSilicone Straws: https://bit.ly/2PIIbWD \nCeramic knives: http://bit.ly/2xA2WdC\nSilicone Storage Bags: http://bit.ly/2Cf1S1P\nLemon Citrus Squeezer: http://bit.ly/2CDZHpF \nGreens Powder (Mixed Berries): https://bit.ly/2G1pbB1\nReishi Defense Supplement: https://bit.ly/32vCeC6\nOsteo Cal-Mag Supplement: https://bit.ly/31tgCal\nDigest Best Supplement: https://bit.ly/3hBw3Ty\nBlender: https://amzn.to/2MPcJr9 \nMini Food Processor: https://amzn.to/2XwqFYF \nPop-Up Storage Container: http://bit.ly/2XVnhtG \nStand Mixer: https://amzn.to/2Ic6uuf \nSilicone Baking Tool Set: http://bit.ly/30yDIKn \n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/GW7ik6G0uZM/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "healthy recipes",
      "healthy cooking channel",
      "healthy food",
      "easy meals",
      "easy dinner ideas",
      "clean eating",
      "detox recipes",
      "salads",
      "smoothies",
      "healthnut nutrition",
      "food channel",
      "quick meals",
      "how to cook",
      "healthnut",
      "food",
      "recipes",
      "easy recipes",
      "healthy breakfast ideas",
      "healthy back to school lunches",
      "healthy snacks",
    ],
    duration: "PT14M12S",
    dimension: "2d",
    definition: "hd",
    viewCount: "263808",
    likeCount: "3982",
    dislikeCount: "69",
    favoriteCount: "0",
    commentCount: "195",
  },
  {
    id: "yI3oPMZ1ETc",
    publishedAt: "2020-08-19T19:02:02Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "DETOX YOUR HOME | 7 Simple Non Toxic Swaps",
    description:
      "ORDER NOW! The HealthNut Cookbook\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nToday I'm sharing 7 products that I've ditched over the years and what I'm using instead as a safer, non-toxic alternative! A special thank you to Arm & Hammer for sponsoring and collaborating with me on the video and for keeping my teeth clean with only the essential ingredients. What are some product swaps that you've recently made in your non-toxic journey? Leave them in the comments below :) \n\nYou can buy this amazing toothpaste here: https://amzn.to/349CIjQ  \n\nFor more information about the ingredients in the toothpaste click here: https://bit.ly/3kVuBNL \n\nIf you’re looking for a toothbrush swap, you’re in luck because Arm & Hammer has the charcoal-infused Spinbrush, available on here https://amzn.to/3heRytm or at Wal Mart here https://bit.ly/2EbCpua \n\nPRODUCTS MENTIONED:\nPit Refresh Natural Deoderant: http://bit.ly/32S2uVu\nBamboo Toothbrush (similar): https://amzn.to/32921jl\nDryer Balls: https://amzn.to/2CFhyyL\nEssential Oils: https://bit.ly/3etUBgb \nAll-Natural Cleaner: https://bit.ly/39bejt8\nMini Funnels: https://bit.ly/3l10ftd\nDetail Cleaning Brush: https://bit.ly/3ahuXbK\nNatural Mascara:  https://rstyle.me/+nEq2lVvs1aeWGxEvJqv5Eg\nNatural Concealer: https://rstyle.me/+BMgmTrqCA9GpFzhsKuWs-Q\nNatural Blush: https://rstyle.me/+kmvnoXS8x4aWKPEGlY7ftA\nNatural Setting Powder: https://rstyle.me/+N3DyFLtAAN_dsYnuk3OxP\nNatural Face Bronzer:  https://rstyle.me/+6ULYTf6lXqQW9XykmpH2ag\nCC Cream (in tan): https://amzn.to/2Mwefu8 \nFruit & Veggie Cleaning Brush: https://bit.ly/3cfVuat \nFruit & Veggie Wash: https://rstyle.me/+JXVmqHj9xY164VxR803Kxg (sold out) ; https://rstyle.me/+wrqiwGRCaCT1l24tst7QFQ (similar)\nSilicone Baking Mat: http://bit.ly/2FBBwG5\nSilicone Storage Bags: https://bit.ly/3iWaFJ6\n \nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/yI3oPMZ1ETc/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "natural beauty products",
      "best natural beauty product swaps",
      "best natural product swaps",
      "natural product swaps",
      "product swaps",
      "swaps product type",
      "try this not that",
      "clean product swaps",
      "green beauty",
      "zero waste",
      "zero waste beauty",
      "all natural beauty",
      "clean beauty routine",
      "best natural product swap",
      "product swaps 2020",
      "minimal beauty routine",
      "essential oils",
      "healthnut",
      "healthnut nutrition",
      "natural beauty",
      "eco friendly",
      "zero waste swaps",
      "arm and hammer",
      "clean beauty",
    ],
    duration: "PT13M56S",
    dimension: "2d",
    definition: "hd",
    viewCount: "242197",
    likeCount: "1142",
    dislikeCount: "31",
    favoriteCount: "0",
    commentCount: "125",
  },
  {
    id: "eiMZbLiKZZI",
    publishedAt: "2020-07-15T19:04:09Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "5 MUST HAVE SUMMER DIYS | Non Toxic + Eco Friendly",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nToday I'm sharing 5 Must-Have Summer DIYS that are completely Non-Toxic and Eco-Friendly! These recipes are easy, affordable and perfect to use for the whole family to help you survive summer - naturally! Be sure to grab the full-recipes over on the blog (link below) and let me know in the comments which one you're most excited to make first. Happy Summer, HealthNuts!\n\nLinks Mentions:\nEssential Oils Starter Kit: https://bit.ly/3etUBgb \nFREE Essential Oils 101 Course: https://mailchi.mp/healthnutnutrition/oils101 \nFREE Summer Essential Oil Survival Guide PDF: https://bit.ly/2WmUdsm\n5 Must-Have Summer DIYs | Non-Toxic + Eco-Friendly Blog Post (+ RECIPES): https://bit.ly/32kr4BP\n\nRecipes Mentioned:\n1:00 After Sun Spray\n1:29 Bug Spray\n2:52 After Bite\n3:30 Bug Off Body Oil \n5:08 Bug Bomb Diffuser Blend\n\nProducts Mentioned:\nEssential Oils: https://bit.ly/3etUBgb \nCordless Diffuser: https://rstyle.me/+4N20lTBTgGnobKOUteDmug \nAmber Spray Bottles: https://amzn.to/32hXQUk\nWitch Hazel: https://rstyle.me/+esHwB0ycZiwMw1ZeRo-D1Q\nRoller Bottles: https://amzn.to/3fzN27C\nCoconut Oil: https://amzn.to/3evH7PL\nBody Oil Jar: https://bit.ly/3hesNgW\n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\n\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/healthnutnut...\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel, I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/eiMZbLiKZZI/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "6-10-20",
      "natural",
      "affordable",
      "diy",
      "recipes",
      "essential oils",
      "non toxic",
      "homemade",
      "handmade",
      "do it yourself",
      "young living",
      "essential oils for skin",
      "non toxic recipes",
      "diy after bite",
      "natural bug spray",
      "natural sunscreen",
      "summer survival guide",
      "all natural summer products",
      "diy body oil",
      "healthnut nutrition",
      "healthnut nutrition skin care",
      "essential rewards",
      "summer essential oils",
      "essential oil recipes",
      "life hacks",
      "local",
    ],
    duration: "PT7M13S",
    dimension: "2d",
    definition: "hd",
    viewCount: "17420",
    likeCount: "727",
    dislikeCount: "18",
    favoriteCount: "0",
    commentCount: "67",
  },
  {
    id: "4Sb_XPECuWw",
    publishedAt: "2020-06-24T19:00:24Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "Relaxing Night Time Routine | Hacks to Get a Better Sleep",
    description:
      "GET UP TO 50% OFF + an additional 15% OFF your Four Sigmatic order! Click: https://www.foursigmatic.com/healthnutnutrition1\n\n(Discount code auto-applied at checkout)\n\n* International shipping is available.\n\nSURPRISE UPDATE:  Four Sigmatic’s Annual Summer Sale is happening NOW! This is a huge opportunity to get your favorite products at a massive discount.  If you’ve been curious about trying the ‘shroom’ trend, now you can get UP TO 50% off your favorite Mushroom Drinks! Plus if things couldn’t get any better, you can click my link above and receive an ADDITIONAL 15% off on top of the sale and Free Shipping on orders of $50 or more. Discount code is auto-applied at checkout. This sale only happens a few times a year and ends on June 29, 2020 so act quickly!\n\nToday I’m sharing my Relaxing Night Time Routine and Hacks to Get a Better Sleep! huge thanks to Four Sigmatic for sponsoring this video and helping to support the HealthNut Community one shroom at a time! \n\nMY PERSONAL MEDICINAL MUSHROOM FAVS! \n– Golden Latte: make your skin glow with beautifying shiitake and turmeric.\n– Chaga: perfect for the morning to help start the day off right.\n– Chai Latte: Great for the gut, support your “second brain” with a comforting cup of classic chai!\n– Reishi: great in the evening as a relaxing nightcap.\n\nNOTE: All of the mushrooms can also be consumed throughout the day, whenever they are needed most! The entire Four Sigmatic catalogue is vegan, gluten-free and super affordable! **\n\nLINKS MENTIONED:\nFree Essential Oils 101 Course: https://mailchi.mp/healthnutnutrition/oils101\nMy Simple & Natural Skincare Routine: https://bit.ly/36t4K9h\nFollow Cashew on Instagram: http://bit.ly/2PIApva \n\nPRODUCTS SEEN/MENTIONED:\nMilk Frother: https://amzn.to/2P4ZAbR\nDiffuser: https://bit.ly/3etUBgb\nEssential Oils: https://bit.ly/3etUBgb \nReclaimed Wood Dresser: https://bit.ly/2CAvYQv\nThe HealthNut Cookbook: http://bit.ly/33XUK5l\nVacuum: https://amzn.to/2UmL6Vw\nGlass kettle: https://amzn.to/2GBWoRT \nDog Food: https://bit.ly/36ATtUk \nHarness: https://amzn.to/2D2a5XM \nCooking utensil set: http://bit.ly/2MGMtwU\nRosewater Toner (use HEALTHNUT15 for 15% off your order!): http://bit.ly/2kD0Rv6\nJojoba Oil: https://amzn.to/2sBFWsG\nLip Butter: http://bit.ly/2XfQH2j\nEssential Oil Display Case: https://rstyle.me/+vvenXQrFaRHUglry_IEbng \nBlue Light Glasses: https://bit.ly/2YrdwSR\n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for your support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/4Sb_XPECuWw/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "nightime routine",
      "nighttime routines 2020",
      "my nighttime routines for summer",
      "night time routine",
      "nighttime routine",
      "routine",
      "relaxing night time routine",
      "how to get a better sleep",
      "sleep hacks",
      "sleep hygiene",
      "healthy recipes",
      "dinner ideas",
      "easy recpies",
      "healthy",
      "get unready with me",
      "skincare routine",
      "my skincareroutine",
      "skincare",
      "skincare products",
      "four sigmatic",
      "wellness",
      "lifestyle",
      "healthnut",
      "healthnut nutrition",
      "healthnut eats",
    ],
    duration: "PT14M51S",
    dimension: "2d",
    definition: "hd",
    viewCount: "35899",
    likeCount: "1329",
    dislikeCount: "21",
    favoriteCount: "0",
    commentCount: "81",
  },
  {
    id: "XnagWZ99jpM",
    publishedAt: "2020-06-10T19:02:13Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "11 Beauty Products I DON'T Buy Anymore",
    description:
      "ORDER NOW! The HealthNut Cookbook\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \nSign Up for our FREE Essential Oils 101 Course: https://bit.ly/2TsYDMO\n\nHey HealthNuts! Today I'm sharing 11 beauty products that I don't buy anymore, and the all-natural alternatives that I used in their place! These non-toxic swaps are simple, effective and so much better for your health! What product swaps have you guys made in your routine? Let me know in the comments below😊\n\nLINKS MENTIONED:\n11 Beauty Products I Don't Buy Anymore Blog Post + DIY Body Scrub recipe: https://bit.ly/30sIH1l\nBeautyNut Skincare Line: http://bit.ly/2NuCNGm\nMy Simple & Natural Skincare Routine: https://bit.ly/36t4K9h\n\nPRODUCTS MENTIONED:\nEssential Oils: https://bit.ly/3etUBgb \nJojoba Oil: https://amzn.to/2sBFWsG\nFace Towels: https://amzn.to/30pVP7v\nWicker Basket: https://rstyle.me/+BqB-0xafiQlHVRlf3-mX1A\nCoconut Oil: https://amzn.to/3cOqZbp\nLemongrass Soap Bar: http://bit.ly/33r0gxw\nFresh Tangerine Soap Bar: http://bit.ly/36VAS5k\nLoofa (similar): https://rstyle.me/+lS-j05JSjno76enK7G27XQ\nDry Shampoo: https://rstyle.me/+0LYV1vjYeGkJrrKkueXk7w + https://bit.ly/2MWmQYt\nRose Water Toner:  http://bit.ly/2kD0Rv6\nMinty Clean Oil Pull: https://bit.ly/3hesNgW\n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/XnagWZ99jpM/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "natural beauty products",
      "best natural beauty product swaps",
      "best natural product swaps",
      "natural product swaps",
      "product swaps",
      "swaps product type",
      "try this not that",
      "oil product swaps",
      "clean product swaps",
      "green beauty",
      "zero waste",
      "zero waste beauty",
      "all natural beauty",
      "clean beauty routine",
      "best natural product swap",
      "product swaps 2020",
      "minimal beauty routine",
      "essential oils",
      "coconut oil",
      "healthnut",
      "healthnut nutrition",
      "natural beauty",
      "fav natural beauty products",
    ],
    duration: "PT22M1S",
    dimension: "2d",
    definition: "sd",
    viewCount: "24753",
    likeCount: "944",
    dislikeCount: "21",
    favoriteCount: "0",
    commentCount: "91",
  },
  {
    id: "03f7uqvLrDs",
    publishedAt: "2020-04-24T17:52:49Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "20 Healthy Pantry MUST HAVES + Printable Shopping List",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nGet Your FREE Healthy Pantry Staples Printable here: https://bit.ly/3butRKu\nTry these 12 Easy Pantry Staple Recipes: https://bit.ly/3bz9ADH\n\nHey HealthNuts! Today I'm sharing 20 Healthy Pantry Essentials that I always have stocked in my kitchen. These items are affordable, extremely versatile and will help you make easy and delicious meals any day of the week. Don't forget to download a FREE printable shopping list and check out the links below to use as guidance while you re-stock your pantry! What are 3 pantry staples that you can't live without? Let me know in the comments below😊\n\nRecipes/Links Mentioned:\nBanana Bread Muffins (IGTV): https://bit.ly/34YCjzl\nBanana Oat Pancakes: http://bit.ly/2CiE8L5\nGluten-Free Flour Blend (Flour 101 Guide): http://bit.ly/2Kl2f1e\nHoney Roasted Sriracha Cashews: http://bit.ly/2XKGzSv\nPumpkin Alfredo: http://bit.ly/2dzJoO9\nButternut Squash Lasagna Roll-Ups: http://bit.ly/3aNl7yl:\nGlass Storage Container with Wood Lid (Small): https://rstyle.me/+MjbiyLNhaRetkP5fOjasMQ\nGlass Storage Container With Wood Lid (Large): https://rstyle.me/+EwLccC19SXAGABfD27PKfA \nBon Appetite Bean Video: https://www.youtube.com/watch?v=PXqoyt4vsPA\n\nProducts Mentioned:\nOat Milk: https://rstyle.me/+VfibiV4eYBuLOMXoOdvE8w \nApple Cider Vinegar: https://amzn.to/2Y560x5\nNutritional Yeast: https://amzn.to/3cKhLgE\nCoconut Butter: https://amzn.to/3bCiYGK\nCanned Chickpeas: https://amzn.to/2Vzca70\nRolled Oats: https://amzn.to/353cRIJ\nCoconut Milk: https://amzn.to/3asgx8c\nBouillon Cubes: https://amzn.to/2Y7QPmG\nAvocado Oil: https://rstyle.me/+EIwwQZg_yN1QzVSbBKHubw \nSpelt Flour: https://amzn.to/34YyHgI\nRaw Cashews: https://amzn.to/34ZZBoo\nMedjool Dates: https://amzn.to/34Zxrd2\nCanned Salmon (similar): https://rstyle.me/+ulYe_NdiHoEsPKo4gtp12A\nChickpea Pasta: https://amzn.to/357vOtZ\nQuinoa Pasta: https://amzn.to/3cDXYza\nQuinoa: https://amzn.to/3awkQ2o\nPumpkin Puree: https://amzn.to/2S41Dyr\nCoconut Sugar: https://amzn.to/2yHwGct\nProtein Powder: https://amzn.to/3axImfn\nCanned Tomatoes: https://amzn.to/3bBdpIj\nChocolate Chips (similar): https://amzn.to/352ewP5 \n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\n\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel, I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/03f7uqvLrDs/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "pantry essentials",
      "pantry basics",
      "cupboard essentials",
      "pantry food",
      "pantry recipes",
      "easy recipes",
      "healthy recipes",
      "healthy pantry recipes",
      "pantry staples",
      "kitchen essentials",
      "healthy food staples",
      "healthy pantry list",
      "pantry list",
      "grocery shopping list",
      "healthnut eats",
      "healthnut nutrition",
      "healthnut",
      "healthy hacks",
      "healthy",
    ],
    duration: "PT25M23S",
    dimension: "2d",
    definition: "hd",
    viewCount: "55124",
    likeCount: "1622",
    dislikeCount: "42",
    favoriteCount: "0",
    commentCount: "109",
  },
  {
    id: "7n0vy6bIW8E",
    publishedAt: "2020-03-04T20:00:14Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 Digital Detox Habits to Reduce Stress and Boost Productivity!",
    description:
      "ORDER NOW! The HealthNut Cookbook\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nToday I'm collaborating with the wellness expert and my friend Meghan Livingstone to share 7 Digital Detox Habits to Reduce Stress and Boost Productivity! Got any tips of your own? Leave them in the comments below! \n\n7 Digital Detox Habits to Start Now Blog Posts: http://bit.ly/2ImwcKK\n\nWatch Meghan's Video:  https://youtu.be/Dd60OC_dCCw\nSubscribe to Meghan's Channel: http://bit.ly/2IfZlHr\n\nLINKS MENTIONED:\nHealthNut Shop: http://bit.ly/2FJb42N\nFlume App: http://bit.ly/3aq8aKM \n\nPRODUCTS SEEN/MENTIONED:\nBeautyNut Lip Butter: http://bit.ly/2XfQH2j\nBook: https://amzn.to/3apNv9I\nBlue Light Glasses: https://www.bonlook.com/ca/en/women/eyeglasses/london/blush\n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/7n0vy6bIW8E/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "digital detox",
      "digital detox habits",
      "digital detox tips",
      "digital minimalism",
      "social media",
      "social media boundaries",
      "how to digital detox",
      "detox",
      "minimalism",
      "unplug",
      "recharge",
      "digital minimalist",
      "blue light glasses",
      "productivity",
      "productivity hacks",
      "reduce stress",
      "how to reduce stress and anxiety",
      "healthy lifestyle",
      "social media detox",
      "meghan livingstone",
      "healthnut",
      "healthnut nutrition",
    ],
    duration: "PT18M34S",
    dimension: "2d",
    definition: "hd",
    viewCount: "21457",
    likeCount: "763",
    dislikeCount: "16",
    favoriteCount: "0",
    commentCount: "57",
  },
  {
    id: "qH5FpREDao4",
    publishedAt: "2020-02-12T20:07:00Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "10 Life-Changing Baking Hacks That You NEED To Know!",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nSubscribe to our the Newsletter for a FREE Flour 101 Guide: https://mailchi.mp/healthnutnutrition/flourguide\n\nHey HealthNuts! Today I'm sharing 10 life-changing baking hacks that are going to make a much cleaner, quicker, and more enjoyable experience in the kitchen! What are your best baking hacks or tips that you swear by? Leave me a comment below with all of your secrets. ;) \n\n10 Life-Changing Baking Hacks Blog Post: http://bit.ly/31Oryhi\n\nRecipes Mentioned:\nOne Bowl Carrot Cake Muffins (from the HealthNut Cookbook): http://bit.ly/2T4oSKb\nNew Fashioned Chocolate Chip Cookies (from the HealthNut Cookbook): http://bit.ly/2T4oSKb\nBanana Bread: http://bit.ly/29tYFR0\n\nProducts Mentioned:\nStand Mixer: https://amzn.to/2Ic6uuf \nSilicone Baking Tool Set: http://bit.ly/30yDIKn \nCookie Scoop: http://bit.ly/2uLMhmd\nSilicone Baking Mat: http://bit.ly/2FBBwG5\nDry Measuring Cups (similar): https://amzn.to/31PQQf5\nWet Measuring Cups (similar): https://rstyle.me/+TC3D2i7przKjaGTqkqq1eA\nCeramic knives: http://bit.ly/2xA2WdC\n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\n\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel, I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/qH5FpREDao4/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "baking",
      "baking hacks",
      "life changing baking hacks",
      "baking 101",
      "baking for beginners",
      "gluten free",
      "aquafaba",
      "egg replacer",
      "hacks",
      "baking tips",
      "gluten free bread",
      "healthy carrot cake muffins",
      "healthy chocolate chip cookies",
      "bake",
      "health nut",
      "healthnut nutrition",
      "how to ripen your bananas",
      "silicone baking mat",
      "zero waste baking",
      "easy recipes",
      "recipes",
      "healthy",
      "must know baking hacks",
      "10 baking hacks",
    ],
    duration: "PT9M36S",
    dimension: "2d",
    definition: "hd",
    viewCount: "30493",
    likeCount: "1384",
    dislikeCount: "24",
    favoriteCount: "0",
    commentCount: "69",
  },
  {
    id: "9f3j_MVDYwg",
    publishedAt: "2020-01-29T20:44:40Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 Life Changing Healthy Habits to Start TODAY!",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nSign up for the newsletter and get my FREE green smoothie guide: https://mailchi.mp/healthnutnutrition/greensmoothieguide  \n\nHappy 2020 HealthNuts! In today’s video, I’m sharing 7 Healthy Habits to help get you back on track. These are simple, straight forward and realistic habits that will make a big impact and have you feeling your best in the New Year! Which healthy habits do you feel most inspired to start implementing today? Let me know in the comments below! \n\nA huge thank you to Enerex for sponsoring this video and supporting the HealthNut community. For more information about their supplements, click here to visit their website: http://bit.ly/Enerex  \n\n7 Healthy Habits To Start Today Blog Post: http://bit.ly/318ay5f\n\nGo-To Meal Prep Recipes:\nKale & Quinoa Stir-Fry: http://bit.ly/2pVXhuY\n5 Easy Bento Box Lunches: http://bit.ly/2EQmwVy\nRaw Chocolate Cookie Dough Balls: http://bit.ly/2JSgNlD (from the cookbook)\nCreamy Chickpea Curry: http://bit.ly/2wr6oGM\nChia Pudding Fruit Parfaits 3 Ways: http://bit.ly/2LtrrSx\nFor more of my meal prep recipes click HERE: http://bit.ly/2ObzF1T\n\nProducts Mentioned:\nHealthNut Water Bottle: http://bit.ly/2rgiUWV\nCeramic knives: http://bit.ly/2xA2WdC \nPop Up Storage Container (small) : http://bit.ly/2XVnhtG \nBlender: https://amzn.to/2MPcJr9\nGlass Straws: http://bit.ly/2HKEp9s\nAirpods Case (Similar): https://amzn.to/34OC5df\nEssential Oils: https://www.healthnutnutrition.ca/essential-oils/sponsorid=21450614&enrollerid=21450614\nWhite Diffuser: http://bit.ly/2rW5GTk\nDiffuser House: https://amzn.to/2M266Pb\nSteam Mop: https://amzn.to/38Cw31J\nSilicone Baking Mat: http://bit.ly/2FBBwG5\nSilicone Baking Tool Set: http://bit.ly/30yDIKn \nStand Mixer: https://amzn.to/2Ic6uuf \nLarge Ice Cream Scoop: http://bit.ly/2uLMhmd\nGlass Storage Containers: http://bit.ly/2Yjrd72 \nSilicone Storage Bags (Stand Up ): http://bit.ly/2rrUpdG \nSilicone Storage Bags: http://bit.ly/2RnJXMD \n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\n\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/9f3j_MVDYwg/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "healthy habits",
      "change your life",
      "how to be healthy",
      "7 healthy habits",
      "2020 goals",
      "new year's resolutions",
      "healthy",
      "greens powder",
      "green smoothie",
      "healthy smoothie recipes",
      "enerex",
      "healthy hacks",
      "daily habits",
      "motivation",
      "inspiration",
      "wellness",
      "lifestyle",
      "meal prep",
      "meal prep hacks",
      "healthnut",
      "healthnut nutrition",
      "recipes",
      "easy recipes",
    ],
    duration: "PT11M42S",
    dimension: "2d",
    definition: "hd",
    viewCount: "169137",
    likeCount: "3232",
    dislikeCount: "56",
    favoriteCount: "0",
    commentCount: "146",
  },
  {
    id: "Hmv2eQGX_Rw",
    publishedAt: "2020-01-15T20:24:17Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "The BEST Fridge Organization Hacks | What's In My Fridge",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nSign up for the newsletter and get a FREE recipe sneak peek from The HealthNut Cookbook: https://mailchi.mp/75b761a1a644/cookbookrecipe\n\nWatch my 10 Foods I Buy Every Week Video: http://bit.ly/2DS56K3\n\nProducts Mentioned:\nEssential Oils: https://www.youngliving.com/vo/#/signup/new-start?sponsorid=21450614&enrollerid=21450614\nOrganization Shelves (small) https://amzn.to/2tmLwCX\nOrganization Shelves (medium/long): https://amzn.to/30yTHIR\nOrganization Shelves (large) :https://amzn.to/3acwH6L\nOrganization Shelves (soda cans): https://amzn.to/30mUdt2\nPop Lid Storage Containers: http://bit.ly/2XVnhtG \nAbsorbent Pads (similar): https://amzn.to/2soFn93\nAvocado Hugger: http://bit.ly/2XyT9QY \nSilicone Storage Bag: http://bit.ly/2Cf1S1P\nSilicone Storage Bags (Stand Up): http://bit.ly/2rrUpdG\nSilicone Storage Bags (Jumbo): http://bit.ly/2RnJXMD  \nSilicone Storage Bags (mini): http://bit.ly/34QNpW5\nWide Mouth Mason Jars: https://amzn.to/2QRAXAK\nSmall Mason Jars (similar): https://amzn.to/2uQG1Nz\nMason Jar Lids: https://amzn.to/2TmKy4h\nEgg Organizer: https://amzn.to/3a9OpHY\nProduce Container: https://amzn.to/2QTl50T\nLazy Susan: https://amzn.to/2thjUPM\nWater Container: https://amzn.to/2tXnkHl\n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\n\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram •  http://Instagram.com/healthnutnutrition\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/Hmv2eQGX_Rw/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "what's in my fridge",
      "what i eat in a week",
      "what i eat in a day",
      "whats in my fridge",
      "fridge",
      "fridge tour",
      "healthy food",
      "weight loss",
      "grocery haul",
      "fridge hacks",
      "fridge organization ideas",
      "my fridge",
      "kitchen tour",
      "healthy meal ideas",
      "meal prep with me",
      "health nut nutrition",
      "healthnut",
      "healthy",
      "healthy food staples",
    ],
    duration: "PT19M17S",
    dimension: "2d",
    definition: "hd",
    viewCount: "81368",
    likeCount: "1831",
    dislikeCount: "56",
    favoriteCount: "0",
    commentCount: "106",
  },
  {
    id: "oxrO-Q0HKWg",
    publishedAt: "2019-09-25T18:59:53Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "5 Underrated Healthy Foods that you MUST TRY!",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nDon't you just love foods that are healthy but taste amazing too?! (It's the little things😉) Today I'm sharing 5 underrated foods that you MUST TRY because I just don't think get the love they deserve! Have you guys tried these foods before? Let me know in the comments below!\n\nProducts mentioned in this video:\nNutritional yeast: https://amzn.to/2n7YvoC\nCoconut mana: https://amzn.to/2ngGxR5\nCarob powder: https://amzn.to/2lI8z7z\nWater chestnuts: https://amzn.to/2mK7Q5M\nChinese five-spice: https://amzn.to/2nhtDSR \nCeramic non-stick frying pans: https://amzn.to/31qAOXz\nSmall storage container: http://bit.ly/2Yjrd72 \nLarge storage container: http://bit.ly/2ng9Mn3\nBlender: https://amzn.to/2MPcJr9 \n\nShop My Amazon Store:  https://amzn.to/2wSWCOc \n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/oxrO-Q0HKWg/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "5 underrated healthy foods",
      "5 foods you must try",
      "what i eat in a day",
      "healthy recipe ideas",
      "healthy recipes",
      "healthy food",
      "healthy food channel",
      "what to buy at the grocery store",
      "nutritional yeast",
      "healthy grocery haul",
      "what i eat in a week",
      "health nut nutrition",
      "underrated",
      "nutrition",
      "foods you must try",
      "clean eating",
      "healthy fats",
      "pantry essentials",
      "what's in my pantry",
    ],
    duration: "PT11M6S",
    dimension: "2d",
    definition: "hd",
    viewCount: "67716",
    likeCount: "1674",
    dislikeCount: "40",
    favoriteCount: "0",
    commentCount: "109",
  },
  {
    id: "HUOpkwbDM-c",
    publishedAt: "2019-09-18T19:01:07Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "8 TIME-SAVING Meal Prep HACKS | Back to School Edition!",
    description:
      "ORDER NOW! The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \nRSVP Virtual dinner with Nikole: https://mailchi.mp/b1c679a91589/dinner_with_nikole\n\nToday I'm sharing my 8 TIME-SAVING meal prep hacks just in time for back to school season! Even if you're not a student (like myself), these tricks can apply to anyone who is looking to step up their meal prepping game by making healthy and delicious foods and save time while doing it! Trust me, your future self will thank you later.😉\n\nCheck out the full blogpost + recipes HERE: http://bit.ly/2mnDGW2\n\nProducts/Links Mentioned:\nSilicone ice cube tray: https://amzn.to/2sIRZ7l\nGlass straws: http://bit.ly/2HKEp9s  \nCeramic knives: http://bit.ly/2xA2WdC\nLemon citrus squeezer: http://bit.ly/2CDZHpF \nLarge white mason jar: https://amzn.to/2RM3VnY\nLarge ice cream scoop: http://bit.ly/2uLMhmd\nWide mouth jar white lids: https://amzn.to/2S76X5i\n3 layer stacked bento box: http://bit.ly/2KOijnp\nGlass storage containers: http://bit.ly/2Yjrd72 \nJumbo silicone storage bags: http://bit.ly/2RnJXMD \n\nShop My Amazon Store:  https://amzn.to/2wSWCOc \n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/HUOpkwbDM-c/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "meal prep hacks",
      "back to school",
      "meal prep ideas",
      "back to school lunches",
      "healthy hacks",
      "easy meal prep",
      "meal prep tips",
      "kitchen hacks",
      "kitchen tips",
      "beginner meal prep",
      "what i eat in a day",
      "meal prep for the week",
      "health nut nutrition",
      "healthy recipes",
      "lunch prep",
      "clean eating",
      "healthy food",
      "healthy lunch ideas",
    ],
    duration: "PT9M52S",
    dimension: "2d",
    definition: "hd",
    viewCount: "482387",
    likeCount: "19155",
    dislikeCount: "166",
    favoriteCount: "0",
    commentCount: "240",
  },
  {
    id: "eKrUQFELktk",
    publishedAt: "2019-05-06T20:48:32Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 MUST KNOW Food Waste Hacks",
    description:
      "Subscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \nNEW Meal Planner and Grocery List Bundle: http://bit.ly/2Id3dde\n\nENTER in the 5k GIVEAWAY Here: http://bit.ly/2V0o5Y9\n\nToday I'm sharing 7 MUST KNOW Food Waste Hacks!\n\n\nGet all recipes and hacks mentioned on the blog HERE: http://bit.ly/2vIIuqp\nFood Hacks Video playlist: http://bit.ly/2DShdX8\nSilicone mat: Baking mat: http://bit.ly/2FBBwG5 \nSilicone bags: http://bit.ly/2Cf1S1P\nCompost bin: http://bit.ly/2HLyrJh \nLarge ice cream scoop: http://bit.ly/2uLMhmd\nGlass straws: http://bit.ly/2HKEp9s\nStainless steel straws: http://bit.ly/2JHkT3b \n\n\n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/eKrUQFELktk/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "meal prep hacks",
      "food waste hacks",
      "easy meal prep",
      "kitchen hacks",
      "food budget tips",
      "mael prep tips",
      "beginner meal prep",
      "must know life hacks",
      "must know meal prep hacks",
      "how to save money in the kitchen",
      "what i eat in a day",
      "eco friendly house",
      "sustainability",
      "fodo waste tips",
      "health nut nutrition",
      "how to cook",
      "zero waste",
      "how to reduce food waste",
      "zero waste hacks",
    ],
    duration: "PT8M56S",
    dimension: "2d",
    definition: "hd",
    viewCount: "110524",
    likeCount: "4324",
    dislikeCount: "58",
    favoriteCount: "0",
    commentCount: "177",
  },
  {
    id: "uRIpRAqzVUg",
    publishedAt: "2019-04-04T17:45:19Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 MUST KNOW Meal Prep Hacks! Part Two",
    description:
      "Subscribe to my channel here ↠ http://bit.ly/1XKeAIi\nSign up to my weekly newsletter here ↠ http://bit.ly/2FwMD6Q\nDownload Green Smoothie Guide here ↠ http://bit.ly/2szBVop\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n\nToday I'm sharing my 7 MUST KNOW meal prep hacks to making meal prepping so much easier! These simple and easy meal prep tips and tricks will change the way you cook in the kitchen. \n\nCheck out the full blogpost HERE: http://bit.ly/2FZJufD\n\nPRODUCTS MENTIONED:\nMeal Planner and Grocery List Bundle: http://bit.ly/2Id3dde\nBlender: https://amzn.to/2X1OO8X \nLarge ice cream scoop: http://bit.ly/2uLMhmd\nCeramic knives: http://bit.ly/2xA2WdC\nGlass straws: http://bit.ly/2HKEp9s\nBaking mat: http://bit.ly/2FBBwG5 \nLarge white mason jar: https://amzn.to/2RM3VnY\nWide mouth jar white lids: https://amzn.to/2S76X5i\nWater filter pitcher: http://bit.ly/2CC588t\nSilicone bags: http://bit.ly/2MtRmuP\nSmall silicone ice cube tray: http://bit.ly/2FNJFJI  \n\nRecipes mentioned:\nShrimp Fajita Sheet Pan Dinner: http://bit.ly/2p7v04w\nChili Basil Fish and Veggie Sheet Pan Dinner: http://bit.ly/2EfyB8G\nPerfect Green Smoothie: http://bit.ly/2CVxwlW\n\n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/uRIpRAqzVUg/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "meal prep hacks",
      "easy meal prep",
      "easy meal prep ideas",
      "meal prep tips",
      "kitchen hacks",
      "kitchen tips",
      "food tips and tricks",
      "beginner meal prep",
      "must know life hacks",
      "what i eat in a day",
      "how to cook",
      "meal prep for the week",
      "health nut nutrition",
    ],
    duration: "PT7M57S",
    dimension: "2d",
    definition: "hd",
    viewCount: "615187",
    likeCount: "12230",
    dislikeCount: "451",
    favoriteCount: "0",
    commentCount: "269",
  },
  {
    id: "af8zzqb4Jnw",
    publishedAt: "2019-01-23T20:09:47Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "7 MUST KNOW Meal Prep Hacks!",
    description:
      "Subscribe to my channel here ↠ http://bit.ly/1XKeAIi\nGet my FREE Superfood Guide Ebook here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n\nToday I'm sharing my 7 MUST KNOW meal prep hacks to making meal prepping so much easier! These simple and easy meal prep tips and tricks will change the way you cook in the kitchen. \n\nCheck out the full blogpost HERE: http://bit.ly/2DtFYJk\n\nPRODUCTS MENTIONED:\nLemon squeezer: http://bit.ly/2CDZHpF\nCeramic knives: http://bit.ly/2xA2WdC\nGlass straws: http://bit.ly/2HKEp9s\nFood processor: https://amzn.to/2T8HOon\nSmall food processor: https://amzn.to/2WdTt7e\nLarge white mason jar: https://amzn.to/2RM3VnY\nWide mouth jar white lids: https://amzn.to/2S76X5i\nClear glass mug: https://amzn.to/2zgZQfj\nWater filter pitcher: http://bit.ly/2CC588t\nFood storage pop containers: http://bit.ly/2MrkcZy\nSilicone bags: http://bit.ly/2MtRmuP\nHealthNut water bottle: http://bit.ly/2rgiUWV\nSilicone ice cube tray: https://amzn.to/2sIRZ7l\nBento boxes: http://bit.ly/2HZ6pGU\n\n*I use Grocery Gateway right now for my online grocery shopping. Not sponsored but if you want a $10 off coupon code just email me at nikole@healthnutnutrition.ca and I'll email you the code since they don't have a link. \n \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/af8zzqb4Jnw/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "meal prep hacks",
      "easy meal prep ideas",
      "meal prep tips",
      "kitchen hacks",
      "kitchen tips",
      "food tips and tricks",
      "beginner meal prep",
      "must know life hacks",
      "what I eat in a day",
      "how to cook",
      "vegan meal prep hacks",
      "meal prep for the week",
      "health nut nutrition",
    ],
    duration: "PT9M25S",
    dimension: "2d",
    definition: "hd",
    viewCount: "828310",
    likeCount: "20009",
    dislikeCount: "645",
    favoriteCount: "0",
    commentCount: "470",
  },
  {
    id: "yAhexTqHgdY",
    publishedAt: "2019-06-24T18:43:32Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "10 Foods You SHOULD Buy Frozen instead of Fresh",
    description:
      "PRE-ORDER The HealthNut Cookbook!\nFor Canada: http://www.thehealthnutcookbook.ca \nFor USA: http://www.thehealthnutcookbook.com  \n\nSubscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \n\nToday I'm sharing 10 foods you should be buying frozen instead of fresh and why!\n\n10 Foods I Eat Every Week: http://bit.ly/2DS56K3\n15 Foods I Always Buy Organic: http://bit.ly/2V8fK9x\nCheck out my What I Eat videos HERE: http://bit.ly/2UPtVLE\n\nBlender I use: https://amzn.to/2MPcJr9 \nGlass straws: http://bit.ly/2HKEp9s\nWater filter pitcher: http://bit.ly/2CC588t \nLemon citrus squeezer: http://bit.ly/2CDZHpF \nSmall ice cube tray: http://bit.ly/2FNJFJI \nCeramic knives: http://bit.ly/2xA2WdC\nAvocado hugger: http://bit.ly/2XyT9QY \nStasher bags: http://bit.ly/2Cf1S1P\nJumbo Stasher bag: http://bit.ly/2RnJXMD \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/yAhexTqHgdY/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "10 foods you should buy frozen",
      "10 foods you should",
      "what I eat in a week",
      "frozen foods",
      "grocery haul",
      "easy meal prep",
      "what to buy at the grocery store healthy",
      "dinner ideas",
      "what foods to eat for weight loss",
      "healthy grocery haul",
      "healthnut nutrition",
      "frozen food",
      "food",
    ],
    duration: "PT11M37S",
    dimension: "2d",
    definition: "hd",
    viewCount: "137374",
    likeCount: "3395",
    dislikeCount: "132",
    favoriteCount: "0",
    commentCount: "258",
  },
  {
    id: "gG9BXBb-tew",
    publishedAt: "2019-05-13T19:18:34Z",
    channelId: "UCZB32syI0FFtThd6xkPTRrg",
    title: "10 Common Smoothie Mistakes | What NOT to do!",
    description:
      "Subscribe (It's FREE) to my channel here ↠ http://bit.ly/1XKeAIi\nJOIN the email list here ↠ http://bit.ly/2FwMD6Q\nCheck out the HealthNut Shop here ↠ http://bit.ly/2EPrUbP \nNEW Meal Planner and Grocery List Bundle: http://bit.ly/2Id3dde\n\nToday I'm sharing 10 smoothie tips to make the perfect breakfast smoothie!\n\nFREE Smoothie Guide: https://mailchi.mp/healthnutnutrition/greensmoothieguide\nUnexpected veggie smoothie recipes: http://bit.ly/2KJNpk9\nSmoothie recipes playlist: http://bit.ly/2Cxqgx5\nHigh speed blender: https://amzn.to/2HfTGRK\nBudget friendly blender: https://amzn.to/2LGDygn\nSpirulina powder  https://rstyle.me/n/debny8b6dh7\nProtein powder https://rstyle.me/n/debn48b6dh7 \nCollagen powder: https://amzn.to/2VxyJdU\nSilicone bags: http://bit.ly/2Cf1S1P\nCompost bin: http://bit.ly/2HLyrJh \nGlass straws: http://bit.ly/2HKEp9s\nStainless steel straws: http://bit.ly/2JHkT3b \n______________________\nCamera & Equipment I use to film my videos:\nMain Cam: http://amzn.to/2hKquYm\nLens: https://amzn.to/2ObB8mY\nMain Tripod: http://amzn.to/2uGWCgS\nVlog Tripod: http://amzn.to/2ftVcEG\nMicrophone: http://amzn.to/2vEZGys  \nLights: http://amzn.to/2lQTEE1\nLight Stands: http://amzn.to/2lQTKeR\nHard Drive: http://amzn.to/2CkYZdY\n\nOther Places You Can Find Me :)\nInstagram • http://Instagram.com/urhealthnut\nFacebook • https://www.Facebook.com/urhealthnut\nBlog • http://www.healthnutnutrition.ca \nShop: https://healthnutshop.com/\n\nHey HealthNuts! I'm Nikole and welcome to the HealthNut Fam :) On my channel I talk about all things Food, health, lifestyle, Food, oh and did I mention food? I post 2-3 times a week on my channel. Recipe Mondays, Wellness Wednesdays and Vlog Fridays. I create videos like: What I Eat in a Day, Meal Prep With Me, Healthy Grocery Hauls, Healthy Recipes, My Morning Routine, Day in the Life and MORE! \n\nMost Popular Videos ↠\n7 Meal Prep Hacks  • http://bit.ly/2HxaiXm\nWhat I Eat in a Day at Work • http://bit.ly/2qmkg5c\nMy Spring Cleaning Routine • http://bit.ly/2qgX60h\nMeal Prep for Beginners • http://bit.ly/2lPoqNA\n5 Bento Box Lunch recipes• http://bit.ly/2EQmwVy\n3 Healthy Smoothie Recipes • http://bit.ly/2CzYUHv\nMy Fitness Morning Routine: http://bit.ly/2lP37N4 \n\n*This video is not sponsored. All opinions expressed are my own. I sometimes receive products for free from brands for consideration but will disclose when videos are sponsored and I am getting paid to talk about the brand/products mentioned. Thank you for support. \n\nHugs + Smoothies,\nNikole xo",
    thumbnailUrl: "https://i.ytimg.com/vi/gG9BXBb-tew/maxresdefault.jpg",
    channelTitle: "HealthNut Nutrition",
    tags: [
      "how to make a perfect smoothie",
      "green smoothie",
      "best smoothie ever",
      "how to make a breakfast smoothie",
      "smoothie hacks",
      "smoothie making tips",
      "healthy breakfast recipes",
      "smoothie mistakes",
      "weightloss recipes",
      "health nut nutrition",
      "easy recipes",
      "healthy",
      "recipes",
    ],
    duration: "PT13M58S",
    dimension: "2d",
    definition: "hd",
    viewCount: "1406323",
    likeCount: "22872",
    dislikeCount: "1584",
    favoriteCount: "0",
    commentCount: "1279",
  },
];
